export const typejob = [
    "CNTT - Phần mềm",
    "Ngân hàng",
    "CNTT - Phần cứng / Mạng",
    "Quảng cáo / Đối ngoại",
    "Quản lý điều hành",
    "Tư vấn",
    "Kế toán / Kiểm toán",
    "Tiếp thị trực tuyến",
    "Bán lẻ / Bán sỉ",
    "Mỹ thuật / Nghệ thuật",
    "Tiếp thị / Marketing",
    "Chứng khoán",
    "Bán hàng / Kinh doanh",
    "Quản lý chất lượng ",
    "Bưu chính viễn thông",
    "Y tế / Chăm sóc sức khỏe",
    "Giáo dục / Đào tạo",
    "Điện",
    "Tài chính / Đầu tư",
    "Vận chuyển ",
    "Dịch vụ khách hàng",
    "Xây dựng",
    "Dệt may",
    "Bảo hiểm",
    "Hành chính",
    "Thống kê",
    "Hàng không",
    "Sản xuất",
    "Mới tốt nghiệp",
    "Luật / Pháp lý",
    "Ngành khác",
    "Cơ khí",
    "Tự đông hóa",
];

export const tinhThanhpho = [
    "Hà Nội",
    "Hồ Chí Minh",
    "An Giang",
    "Bà Rịa - Vũng Tàu",
    "Bắc Giang",
    "Bắc Kạn",
    "Bạc Liêu",
    "Bắc Ninh",
    "Bến Tre",
    "Bình Định",
    "Bình Dương",
    "Bình Phước",
    "Bình Thuận",
    "Cà Mau",
    "Cao Bằng",
    "Đắk Lắk",
    "Đắk Nông",
    "Điện Biên",
    "Đồng Nai",
    "Đồng Tháp",
    "Gia Lai",
    "Hà Giang",
    "Hà Nam",
    "Hà Tĩnh",
    "Hải Dương",
    "Hậu Giang",
    "Hòa Bình",
    "Hưng Yên",
    "Khánh Hòa",
    "Kiên Giang",
    "Kon Tum",
    "Lai Châu",
    "Lâm Đồng",
    "Lạng Sơn",
    "Lào Cai",
    "Long An",
    "Nam Định",
    "Nghệ An",
    "Ninh Bình",
    "Ninh Thuận",
    "Phú Thọ",
    "Quảng Bình",
    "Quảng Nam",
    "Quảng Ngãi",
    "Quảng Ninh",
    "Quảng Trị",
    "Sóc Trăng",
    "Sơn La",
    "Tây Ninh",
    "Thái Bình",
    "Thái Nguyên",
    "Thanh Hóa",
    "Thừa Thiên Huế",
    "Tiền Giang",
    "Trà Vinh",
    "Tuyên Quang",
    "Vĩnh Long",
    "Vĩnh Phúc",
    "Yên Bái",
    "Phú Yên",
    "Cần Thơ",
    "Đà Nẵng",
    "Hải Phòng"
];